language: python

python:
  - "2.7"

services:
  - redis-server

install:
  - "pip install webtest coverage nose-cov flake8 python-coveralls --use-mirrors"
  - "pip install -e . --use-mirrors"

before_script: "flake8"

script:  "nosetests"

after_success:
  - coveralls
